import { Coleccion, Producto } from '@/types'

// URLs directas de Wikimedia Commons — fotos reales de velas verificadas
const V1 = 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Scented_candle.jpg'
const V2 = 'https://upload.wikimedia.org/wikipedia/commons/0/01/Scented_candle_candlelight.jpg'
const V3 = 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Mahogany_teakwood_scented_candle_%28cropped%29.jpg'
const V4 = 'https://upload.wikimedia.org/wikipedia/commons/0/08/Mulled_cider_scented_candle.jpg'
const V5 = 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Byredo_1996_scented_candle.jpg'
const V6 = 'https://upload.wikimedia.org/wikipedia/commons/d/df/Scented_candles..._%288610155782%29.jpg'
const V7 = 'https://upload.wikimedia.org/wikipedia/commons/4/41/Scented_candle.png'
const V8 = 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Candle_light_projected_through_a_glass_orb.jpg'
const V9 = 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Candle_With_Gold_Stand.jpg'

export const productosMock: Producto[] = [
  {
    id: '1',
    nombre: 'Lavanda & Bergamota',
    descripcion: 'Una combinación serena de lavanda provenzal y bergamota italiana. Perfecto para crear un ambiente relajante al final del día. La cera de soja garantiza una combustión limpia y prolongada.',
    precio: 24.00,
    imagen_url: V1,
    categoria: 'Otoño',
    stock: 15,
    badge: 'mas-vendido',
    duracion_horas: 45,
    peso_gr: 220,
    notas_aromaticas: ['Lavanda', 'Bergamota', 'Almizcle blanco'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '2',
    nombre: 'Vainilla & Sándalo',
    descripcion: 'La dulzura atemporal de la vainilla de Madagascar fusionada con la profundidad cálida del sándalo. Una fragancia envolvente que convierte cualquier estancia en un hogar.',
    precio: 26.00,
    imagen_url: V2,
    categoria: 'Postre',
    stock: 10,
    badge: 'mas-vendido',
    duracion_horas: 50,
    peso_gr: 240,
    notas_aromaticas: ['Vainilla', 'Sándalo', 'Ámbar'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '3',
    nombre: 'Rosa & Jazmín',
    descripcion: 'Un bouquet floral sofisticado de rosa de Turquía y jazmín de Grasse. Delicada, romántica y atemporal. La elección perfecta para ocasiones especiales o como regalo.',
    precio: 28.00,
    imagen_url: V3,
    categoria: 'Bebidas',
    stock: 8,
    badge: 'nuevo',
    duracion_horas: 45,
    peso_gr: 220,
    notas_aromaticas: ['Rosa', 'Jazmín', 'Iris'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '4',
    nombre: 'Cedro & Ámbar',
    descripcion: 'La fuerza serena del cedro del Atlas encontrándose con la calidez dorada del ámbar. Masculina, sofisticada y profundamente reconfortante. Ideal para espacios de trabajo y meditación.',
    precio: 28.00,
    imagen_url: V4,
    categoria: 'Postre',
    stock: 12,
    duracion_horas: 55,
    peso_gr: 260,
    notas_aromaticas: ['Cedro', 'Ámbar', 'Vetiver'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '5',
    nombre: 'Canela & Naranja',
    descripcion: 'La cálida especiería de la canela de Ceilán con la frescura vibrante de la naranja dulce. Como las tardes de invierno junto al fuego. Un aroma que despierta recuerdos.',
    precio: 22.00,
    imagen_url: V5,
    categoria: 'Hogar',
    stock: 20,
    duracion_horas: 40,
    peso_gr: 200,
    notas_aromaticas: ['Canela', 'Naranja', 'Clavo'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '6',
    nombre: 'Bruma de Mar',
    descripcion: 'La esencia limpia y libre del océano. Notas de sal marina, maderas flotantes y algas frescas. Transporta la brisa del Mediterráneo directamente a tu hogar.',
    precio: 24.00,
    imagen_url: '/vela-oso.jpg',
    categoria: 'Eventos',
    stock: 6,
    badge: 'edicion-limitada',
    duracion_horas: 45,
    peso_gr: 220,
    notas_aromaticas: ['Sal marina', 'Algas', 'Madera de deriva'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '7',
    nombre: 'Higo & Musgo',
    descripcion: 'La frescura vegetal del higo verde con la humedad terrosa del musgo. Un aroma que evoca jardines en la madrugada, íntimo y natural.',
    precio: 26.00,
    imagen_url: V7,
    categoria: 'Eventos',
    stock: 9,
    badge: 'nuevo',
    duracion_horas: 45,
    peso_gr: 220,
    notas_aromaticas: ['Higo', 'Musgo', 'Patchouli'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '8',
    nombre: 'Té Verde & Menta',
    descripcion: 'La delicadeza mineral del té verde japonés con un toque refrescante de menta fresca. Ligera, vigorizante y perfecta para los momentos de claridad mental.',
    precio: 22.00,
    imagen_url: V8,
    categoria: 'Otoño',
    stock: 14,
    duracion_horas: 40,
    peso_gr: 200,
    notas_aromaticas: ['Té verde', 'Menta', 'Bambú'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '9',
    nombre: 'Violeta & Cashmere',
    descripcion: 'La delicadeza floral de la violeta envuelta en la suavidad sedosa del cashmere. Una fragancia íntima y sofisticada para los momentos más especiales.',
    precio: 32.00,
    imagen_url: V9,
    categoria: 'Bebidas',
    stock: 5,
    badge: 'edicion-limitada',
    duracion_horas: 55,
    peso_gr: 260,
    notas_aromaticas: ['Violeta', 'Cashmere', 'Sándalo'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '10',
    nombre: 'Pino & Eucalipto',
    descripcion: 'El aire puro de los bosques del norte. Notas limpias de pino silvestre y eucalipto fresco. Un aroma que purifica el ambiente y despeja la mente.',
    precio: 22.00,
    imagen_url: V1,
    categoria: 'Otoño',
    stock: 18,
    duracion_horas: 40,
    peso_gr: 200,
    notas_aromaticas: ['Pino', 'Eucalipto', 'Cedro'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '11',
    nombre: 'Oud & Rosa Negra',
    descripcion: 'Una fragancia de lujo construida sobre la madera preciosa del oud árabe y los pétalos oscuros de la rosa negra. Intensa, misteriosa e irresistiblemente sensual.',
    precio: 38.00,
    imagen_url: V4,
    categoria: 'Postre',
    stock: 4,
    badge: 'edicion-limitada',
    duracion_horas: 60,
    peso_gr: 300,
    notas_aromaticas: ['Oud', 'Rosa negra', 'Mirra'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '12',
    nombre: 'Pomelo & Jengibre',
    descripcion: 'La energía cítrica del pomelo rosa con el toque picante y cálido del jengibre fresco. Vibrante, optimista y perfecta para comenzar el día con energía.',
    precio: 22.00,
    imagen_url: V3,
    categoria: 'Hogar',
    stock: 16,
    badge: 'nuevo',
    duracion_horas: 40,
    peso_gr: 200,
    notas_aromaticas: ['Pomelo', 'Jengibre', 'Pimienta rosa'],
    creado_en: new Date().toISOString(),
  },
]

export const colecciones: Coleccion[] = [
  {
    id: 'otono',
    nombre: 'Otoño',
    descripcion: 'Fragancias cálidas inspiradas en la estación más sensorial',
    imagen_url: V2,
    categoria: 'Otoño',
  },
  {
    id: 'postre',
    nombre: 'Postre',
    descripcion: 'Aromas dulces y golosos para los momentos de placer',
    imagen_url: V5,
    categoria: 'Postre',
  },
  {
    id: 'bebidas',
    nombre: 'Bebidas',
    descripcion: 'Fragancias inspiradas en las bebidas más evocadoras',
    imagen_url: V8,
    categoria: 'Bebidas',
  },
]
