import { Coleccion, Producto } from '@/types'

// URLs directas de Wikimedia Commons — fotos reales de velas verificadas
const V1 = 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Scented_candle.jpg'
const V2 = 'https://upload.wikimedia.org/wikipedia/commons/0/01/Scented_candle_candlelight.jpg'
const V3 = 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Mahogany_teakwood_scented_candle_%28cropped%29.jpg'
const V4 = 'https://upload.wikimedia.org/wikipedia/commons/0/08/Mulled_cider_scented_candle.jpg'
const V5 = 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Byredo_1996_scented_candle.jpg'
const V7 = 'https://upload.wikimedia.org/wikipedia/commons/4/41/Scented_candle.png'
const V8 = 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Candle_light_projected_through_a_glass_orb.jpg'
const V9 = 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Candle_With_Gold_Stand.jpg'

export const productosMock: Producto[] = [
  {
    id: '1',
    nombre: 'Lavanda & Bergamota',
    nombre_ca: 'Lavanda & Bergamota',
    descripcion: 'Una combinación serena de lavanda provenzal y bergamota italiana. Perfecto para crear un ambiente relajante al final del día. La cera de soja garantiza una combustión limpia y prolongada.',
    descripcion_ca: 'Una combinació serena de lavanda provençal i bergamota italiana. Perfecte per crear un ambient relaxant al final del dia. La cera de soia garanteix una combustió neta i perllongada.',
    precio: 24.00, imagen_url: V1, categoria: 'Otoño', categoria_ca: 'Tardor', stock: 15, badge: 'mas-vendido', duracion_horas: 45, peso_gr: 220,
    notas_aromaticas: ['Lavanda', 'Bergamota', 'Almizcle blanco'],
    notas_aromaticas_ca: ['Lavanda', 'Bergamota', 'Almesc blanc'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '2',
    nombre: 'Vainilla & Sándalo',
    nombre_ca: 'Vainilla & Sàndal',
    descripcion: 'La dulzura atemporal de la vainilla de Madagascar fusionada con la profundidad cálida del sándalo. Una fragancia envolvente que convierte cualquier estancia en un hogar.',
    descripcion_ca: 'La dolçor atemporal de la vainilla de Madagascar fusionada amb la profunditat càlida del sàndal. Una fragància envoltant que converteix qualsevol estança en una llar.',
    precio: 26.00, imagen_url: V2, categoria: 'Postre', categoria_ca: 'Postres', stock: 10, badge: 'mas-vendido', duracion_horas: 50, peso_gr: 240,
    notas_aromaticas: ['Vainilla', 'Sándalo', 'Ámbar'],
    notas_aromaticas_ca: ['Vainilla', 'Sàndal', 'Ambre'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '3',
    nombre: 'Rosa & Jazmín',
    nombre_ca: 'Rosa & Gessamí',
    descripcion: 'Un bouquet floral sofisticado de rosa de Turquía y jazmín de Grasse. Delicada, romántica y atemporal. La elección perfecta para ocasiones especiales o como regalo.',
    descripcion_ca: "Un ram floral sofisticat de rosa de Turquia i gessamí de Grasse. Delicada, romàntica i atemporal. L'elecció perfecta per a ocasions especials o com a regal.",
    precio: 28.00, imagen_url: V3, categoria: 'Bebidas', categoria_ca: 'Begudes', stock: 8, badge: 'nuevo', duracion_horas: 45, peso_gr: 220,
    notas_aromaticas: ['Rosa', 'Jazmín', 'Iris'],
    notas_aromaticas_ca: ['Rosa', 'Gessamí', 'Iris'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '4',
    nombre: 'Cedro & Ámbar',
    nombre_ca: 'Cedre & Ambre',
    descripcion: 'La fuerza serena del cedro del Atlas encontrándose con la calidez dorada del ámbar. Masculina, sofisticada y profundamente reconfortante. Ideal para espacios de trabajo y meditación.',
    descripcion_ca: "La força serena del cedre de l'Atles trobant-se amb la calidesa daurada de l'ambre. Masculina, sofisticada i profundament reconfortant. Ideal per a espais de treball i meditació.",
    precio: 28.00, imagen_url: V4, categoria: 'Postre', categoria_ca: 'Postres', stock: 12, duracion_horas: 55, peso_gr: 260,
    notas_aromaticas: ['Cedro', 'Ámbar', 'Vetiver'],
    notas_aromaticas_ca: ['Cedre', 'Ambre', 'Vetiver'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '5',
    nombre: 'Canela & Naranja',
    nombre_ca: 'Canyella & Taronja',
    descripcion: 'La cálida especiería de la canela de Ceilán con la frescura vibrante de la naranja dulce. Como las tardes de invierno junto al fuego. Un aroma que despierta recuerdos.',
    descripcion_ca: "La calidesa especiada de la canyella de Ceilan amb la frescor vibrant de la taronja dolça. Com les tardes d'hivern al costat del foc. Un aroma que desperta records.",
    precio: 22.00, imagen_url: V5, categoria: 'Hogar', categoria_ca: 'Llar', stock: 20, duracion_horas: 40, peso_gr: 200,
    notas_aromaticas: ['Canela', 'Naranja', 'Clavo'],
    notas_aromaticas_ca: ["Canyella", "Taronja", "Clau d'espècia"],
    creado_en: new Date().toISOString(),
  },
  {
    id: '6',
    nombre: 'Bruma de Mar',
    nombre_ca: 'Broma de Mar',
    descripcion: 'La esencia limpia y libre del océano. Notas de sal marina, maderas flotantes y algas frescas. Transporta la brisa del Mediterráneo directamente a tu hogar.',
    descripcion_ca: "L'essència neta i lliure de l'oceà. Notes de sal marina, fustes flotants i algues fresques. Transporta la brisa del Mediterrani directament a casa teva.",
    precio: 24.00, imagen_url: '/vela-oso.jpg', categoria: 'Eventos', categoria_ca: 'Esdeveniments', stock: 6, badge: 'edicion-limitada', duracion_horas: 45, peso_gr: 220,
    notas_aromaticas: ['Sal marina', 'Algas', 'Madera de deriva'],
    notas_aromaticas_ca: ['Sal marina', 'Algues', 'Fusta a la deriva'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '7',
    nombre: 'Higo & Musgo',
    nombre_ca: 'Figa & Molsa',
    descripcion: 'La frescura vegetal del higo verde con la humedad terrosa del musgo. Un aroma que evoca jardines en la madrugada, íntimo y natural.',
    descripcion_ca: "La frescor vegetal de la figa verda amb la humitat terrosa de la molsa. Un aroma que evoca jardins a la matinada, íntim i natural.",
    precio: 26.00, imagen_url: V7, categoria: 'Eventos', categoria_ca: 'Esdeveniments', stock: 9, badge: 'nuevo', duracion_horas: 45, peso_gr: 220,
    notas_aromaticas: ['Higo', 'Musgo', 'Patchouli'],
    notas_aromaticas_ca: ['Figa', 'Molsa', 'Patchouli'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '8',
    nombre: 'Té Verde & Menta',
    nombre_ca: 'Te Verd & Menta',
    descripcion: 'La delicadeza mineral del té verde japonés con un toque refrescante de menta fresca. Ligera, vigorizante y perfecta para los momentos de claridad mental.',
    descripcion_ca: "La delicadesa mineral del te verd japonès amb un toc refrescant de menta fresca. Lleugera, vigorizant i perfecta per als moments de claredat mental.",
    precio: 22.00, imagen_url: V8, categoria: 'Otoño', categoria_ca: 'Tardor', stock: 14, duracion_horas: 40, peso_gr: 200,
    notas_aromaticas: ['Té verde', 'Menta', 'Bambú'],
    notas_aromaticas_ca: ['Te verd', 'Menta', 'Bambú'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '9',
    nombre: 'Violeta & Cashmere',
    nombre_ca: 'Violeta & Caixmir',
    descripcion: 'La delicadeza floral de la violeta envuelta en la suavidad sedosa del cashmere. Una fragancia íntima y sofisticada para los momentos más especiales.',
    descripcion_ca: "La delicadesa floral de la violeta embolcallada en la suavitat sedosa del caixmir. Una fragància íntima i sofisticada per als moments més especials.",
    precio: 32.00, imagen_url: V9, categoria: 'Bebidas', categoria_ca: 'Begudes', stock: 5, badge: 'edicion-limitada', duracion_horas: 55, peso_gr: 260,
    notas_aromaticas: ['Violeta', 'Cashmere', 'Sándalo'],
    notas_aromaticas_ca: ['Violeta', 'Caixmir', 'Sàndal'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '10',
    nombre: 'Pino & Eucalipto',
    nombre_ca: 'Pi & Eucaliptus',
    descripcion: 'El aire puro de los bosques del norte. Notas limpias de pino silvestre y eucalipto fresco. Un aroma que purifica el ambiente y despeja la mente.',
    descripcion_ca: "L'aire pur dels boscos del nord. Notes netes de pi silvestre i eucaliptus fresc. Un aroma que purifica l'ambient i allibera la ment.",
    precio: 22.00, imagen_url: V1, categoria: 'Otoño', categoria_ca: 'Tardor', stock: 18, duracion_horas: 40, peso_gr: 200,
    notas_aromaticas: ['Pino', 'Eucalipto', 'Cedro'],
    notas_aromaticas_ca: ['Pi', 'Eucaliptus', 'Cedre'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '11',
    nombre: 'Oud & Rosa Negra',
    nombre_ca: 'Oud & Rosa Negra',
    descripcion: 'Una fragancia de lujo construida sobre la madera preciosa del oud árabe y los pétalos oscuros de la rosa negra. Intensa, misteriosa e irresistiblemente sensual.',
    descripcion_ca: "Una fragància de luxe construïda sobre la fusta preciosa de l'oud àrab i els pètals foscos de la rosa negra. Intensa, misteriosa i irresistiblement sensual.",
    precio: 38.00, imagen_url: V4, categoria: 'Postre', categoria_ca: 'Postres', stock: 4, badge: 'edicion-limitada', duracion_horas: 60, peso_gr: 300,
    notas_aromaticas: ['Oud', 'Rosa negra', 'Mirra'],
    notas_aromaticas_ca: ['Oud', 'Rosa negra', 'Mirra'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '13',
    nombre: 'Tarta de Azahar',
    nombre_ca: 'Pastís de Taronja',
    descripcion: 'Una vela inspirada en la repostería mediterránea más delicada. Notas de azahar fresco, almendra tostada y un fondo cálido de vainilla. Como el postre de los domingos en casa de la abuela.',
    descripcion_ca: "Una espelma inspirada en la rebosteria mediterrània més delicada. Notes de flor de taronger fresca, ametlla torrada i un fons càlid de vainilla. Com la postres dels diumenges a casa de l'àvia.",
    precio: 26.00, imagen_url: V2, video_url: '/postre_01.mp4', categoria: 'Postre', categoria_ca: 'Postres', stock: 10, badge: 'nuevo', duracion_horas: 48, peso_gr: 230,
    notas_aromaticas: ['Azahar', 'Almendra', 'Vainilla'],
    notas_aromaticas_ca: ['Flor de taronger', 'Ametlla', 'Vainilla'],
    creado_en: new Date().toISOString(),
  },
  {
    id: '12',
    nombre: 'Pomelo & Jengibre',
    nombre_ca: 'Pomelo & Gingebre',
    descripcion: 'La energía cítrica del pomelo rosa con el toque picante y cálido del jengibre fresco. Vibrante, optimista y perfecta para comenzar el día con energía.',
    descripcion_ca: "L'energia cítrica del pomelo rosa amb el toc picant i càlid del gingebre fresc. Vibrant, optimista i perfecta per començar el dia amb energia.",
    precio: 22.00, imagen_url: V3, categoria: 'Hogar', categoria_ca: 'Llar', stock: 16, badge: 'nuevo', duracion_horas: 40, peso_gr: 200,
    notas_aromaticas: ['Pomelo', 'Jengibre', 'Pimienta rosa'],
    notas_aromaticas_ca: ['Pomelo', 'Gingebre', 'Pebre rosa'],
    creado_en: new Date().toISOString(),
  },
]

export const colecciones: Coleccion[] = [
  {
    id: 'otono',
    nombre: 'Otoño', nombre_ca: 'Tardor',
    descripcion: 'Fragancias cálidas inspiradas en la estación más sensorial',
    descripcion_ca: "Fragàncies càlides inspirades en l'estació més sensorial",
    imagen_url: V2, categoria: 'Otoño', categoria_ca: 'Tardor',
  },
  {
    id: 'postre',
    nombre: 'Postre', nombre_ca: 'Postres',
    descripcion: 'Aromas dulces y golosos para los momentos de placer',
    descripcion_ca: 'Aromes dolços i golafres per als moments de plaer',
    imagen_url: V5, categoria: 'Postre', categoria_ca: 'Postres',
  },
  {
    id: 'bebidas',
    nombre: 'Bebidas', nombre_ca: 'Begudes',
    descripcion: 'Fragancias inspiradas en las bebidas más evocadoras',
    descripcion_ca: 'Fragàncies inspirades en les begudes més evocadores',
    imagen_url: V8, categoria: 'Bebidas', categoria_ca: 'Begudes',
  },
]
